### ISSUE TITLE
Multiple mixin instances

### ISSUE THREAD

**Issue by TheauB** [shdwp/UIExtenderLib#3]
Hi !
I'm using your (great) library and it has been pretty cool so far.
However, i'm facing a problem.

I've created a mixin class for `CraftingAvailableHeroItemVM`.

This class is used in the `CraftingVM` class and is instancied as following : 
```c#
this.AvailableCharactersForSmithing = new MBBindingList<CraftingAvailableHeroItemVM>();
[...]
foreach (Hero hero in CampaignCraftingManager.Instance.GetAvailableHeroesForCrafting())
          this.AvailableCharactersForSmithing.Add(new CraftingAvailableHeroItemVM(hero, new Action<CraftingAvailableHeroItemVM>(this.UpdateCraftingHero)));
```
Ths `CraftingVM`class how has a field `CurrentCraftingHero` which references the selected hero in the Smithing ingame interface.

My problem is the `vm` property in my mixin class always references the last item of the `AvailableCharactersForSmithing` variable not the instance it should be.

I tried to track it and I think it comes from the mecanism around this 2 fields in the `ViewModelComponent`class : 
```c#
private readonly Dictionary<Type, IViewModelMixin> _mixinInstanceCache = new Dictionary<Type, IViewModelMixin>();
private readonly Dictionary<Type, object> _extendedTypeInstanceCache = new Dictionary<Type, object>();
```
Which means it can only have one instance of each mixin type and one reference to the original object.

Am i wrong ? If not do you think about a way to resolve my problem ? I fear it do not fit your implementation

Anyway thanks a lot :)

**Comment by shdwp** [comment]
It has already been fixed on `master` but I haven't pushed a release yet. I hope that I will be able to make a release today.
