### ISSUE TITLE
Correct Harmony version? [Update Harmony version]

### ISSUE THREAD

**Issue by MLNW** [shdwp/UIExtenderLib#7]
We are depending on this library and were wondering why you decided to use Harmony 2.0.0.0 instead of 2.0.0.9, which is the latest release.

https://github.com/shdwp/UIExtenderLib/blob/9d820f978a4df2402bad4e390d133f40c7faef67/UIExtenderLibModule/UIExtenderLibModule.csproj#L35

As far as I can see 2.0.0.0 is targeting .NET 3.5 instead of .NET 4.5 which is usually used for modding Bannerlord. Any reason that I don't see for using the older version?

Also, should dependent mods use the exact same version of Harmony or does that not matter?

**Comment by shdwp** [comment]
That should not matter as soon as both versions are compatible. I will update Harmony version in the upcoming release.

**Comment by shdwp** [comment]
Done in 2.0.0 (awaiting release).
