### ISSUE TITLE
get an issue since 1.5.4

### ISSUE THREAD

**Issue by pkshetlie** [shdwp/UIExtenderLib#9]
hi,
Since the 1.5.4 release of Bannerlord i get the following issue : 

Bannerlord compatibility failure : private value getter on TaleWords.GauntletUI.PrefabSystem.WidgetFactory._customTypes.
...

![Capture](https://user-images.githubusercontent.com/266652/100427654-0fe62980-3093-11eb-89f0-aae5d8b34b0a.PNG)

Thank you for your work, it was really usefull

**Comment by shdwp** [comment]
I don't really maintain this anymore, you may find interest in one of the forks here, it seems to be updated quite often: https://github.com/BUTR/Bannerlord.UIExtenderEx

Sorry for the inconvenience.
